# Site settings
title: "Speech Recognition Course"
description: "A comprehensive course on speech recognition technologies and implementation"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  highlighter: none
  syntax_highlighter: false
  syntax_highlighter_opts:
      disable: true
  parse_block_html: true
  
sass:
  style: :compressed

# Enable plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


exclude:
  - node_modules
  - script
  - Experiments/
  - M1_Introduction/misc/
  - M4_Language_Modeling/srilm/
  - M4_Language_Modeling/data/
  - bak/
  - "*.isym"
  - "*.osym"
  - "*.fst"
  - "*.trn"
  - "*.?gram"
  - "*.docx"
  - "*.odt"
  - "*.txt.gz"

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/bagustris/speech-recognition-course"
  
title: Speech Recognition Course
description: A course on speech recognition
