markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  parse_block_html: true

exclude:
  - node_modules
  - script
  

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/bagustris/speech-recognition-course"
  
title: Speech Recognition Course
description: A course on speech recognition
